import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProbider from "./StoreProbider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vape Shop",
  description: "Generated by create next app",
};

const RootLayout = ({children,}: Readonly<{children: React.ReactNode;}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProbider>
         
          {children}
      
        </StoreProbider>
      </body>
    </html>
  );
};

export default RootLayout;
